version: '3.8'
services:
  database:
    container_name: database-container
    image: "postgres:16.0-alpine"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
      - PGPORT=${DB_PORT}
    volumes:
      - ./database/postgres-data:/var/lib/postgresql/data
      - ./database/init-scripts:/docker-entrypoint-initdb.d
    restart: unless-stopped
    networks:
      - day_planner_network
  server:
    container_name: server-container
    image: server-image
    hostname: server
    build:
      context: ./server/
      dockerfile: Dockerfile
    expose:
      - ${SERVER_PORT}
    ports:
    - "${SERVER_PORT}:${SERVER_PORT}"
    environment:
      - NODE_ENV=production
      - PGDATABASE=${DB_DATABASE}
      - PGUSER=${DB_USER}
      - PGPASSWORD=${DB_PASSWORD}
      - PGHOST=${DB_DATABASE}
    env_file:
      - .env
    depends_on:
      - database
    restart: unless-stopped
    networks:
      - day_planner_network
  frontend:
    container_name: frontend-container
    image: frontend-image
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    expose:
      - ${APP_PORT}
    ports:
      - "${APP_PORT}:${APP_PORT}"
    env_file:
      - ./frontend/.env
      - .env
    depends_on:
      - server
    networks:
      - day_planner_network
    volumes:
      - ./frontend:/app
      - /app/node_modules
    links:
      - server
networks:
  day_planner_network:
    driver: bridge