# frontend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend-container
        image: d1vyansh/frontend-image
        ports:
        - containerPort: 80
        env:
        - name: REACT_APP_WEATHER_API_KEY
          valueFrom:
            secretKeyRef:
              name: frontend-secrets
              key: REACT_APP_WEATHER_API_KEY
      volumes:
      - name: frontend-volume
        emptyDir: {}
