apiVersion: v1
kind: PersistentVolume
metadata:
  name: database-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "C:/Users/DP1372.ZGN/Documents/CODE/day-planner/database/postgres-data"
