apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-volume
  labels:
    app: postgresql
    tier: database
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
